const BASE = 'LOGIN/';

export default {
  LOGIN_EDIT_FIELD: `${BASE}LOGIN_EDIT_FIELD`,
  CHECK_CREDENTIALS: `${BASE}CHECK_CREDENTIALS`,
  UPDATE_LOGIN_STATUS: `${BASE}UPDATE_LOGIN_STATUS`,
  LOGIN_SUCCESSFUL: `${BASE}LOGIN_SUCCESSFUL`,
  EPIC_ADD_TO_WISHLIST: `${BASE}EPIC_ADD_TO_WISHLIST`,
  EPIC_GET_WISHLIST: `${BASE}EPIC_GET_WISHLIST`,
  WISH_LIST_UPDATE: `${BASE}WISH_LIST_UPDATE`
};
