const BASE = 'HOME/';

export default {
  EPIC_TERM_SEARCH: `${BASE}EPIC_TERM_SEARCH`,
  TERM_SEARCH_UPDATE: `${BASE}TERM_SEARCH_UPDATE`,
  RESULTS_UPDATE: `${BASE}RESULTS_UPDATE`,
  SEARCH_TYPE_UPDATE: `${BASE}SEARCH_TYPE_UPDATE`,
  EPIC_ON_FOCUS_SEARCH: `${BASE}EPIC_ON_FOCUS_SEARCH`,
  EPIC_MOVIES_LISTS_UPDATE: `${BASE}EPIC_MOVIES_LISTS_UPDATE`
};
