export const LOGIN_EDIT_FIELD = 'LOGIN_EDIT_FIELD';
export const CHECK_CREDENTIALS = 'CHECK_CREDENTIALS';
export const UPDATE_LOGIN_STATUS = 'UPDATE_LOGIN_STATUS';
export const LOGIN_SUCCESSFUL = 'LOGIN_SUCCESSFUL';
