const BASE = 'LOGIN/';

export const LOGIN_EDIT_FIELD = `${BASE}LOGIN_EDIT_FIELD`;
export const CHECK_CREDENTIALS = `${BASE}CHECK_CREDENTIALS`;
export const UPDATE_LOGIN_STATUS = `${BASE}UPDATE_LOGIN_STATUS`;
export const LOGIN_SUCCESSFUL = `${BASE}LOGIN_SUCCESSFUL`;
export const EPIC_ADD_TO_WISHLIST = `${BASE}EPIC_ADD_TO_WISHLIST`;
export const EPIC_GET_WISHLIST = `${BASE}EPIC_GET_WISHLIST`;
export const WISH_LIST_UPDATE = `${BASE}WISH_LIST_UPDATE`;
