export const EDIT_ID = 'LOGIN_EDIT_ID';
export const EDIT_PASSWORD = 'LOGIN_EDIT_PASSWORD';
export const CHECK_CREDENTIALS = 'LOGIN_CHECK_CREDENTIALS';
export const LOGIN_SUCCESSFUL = 'LOGIN_SUCCESSFUL';
