const BASE = 'HOME/';

export const EPIC_TERM_SEARCH = `${BASE}EPIC_TERM_SEARCH`;
export const TERM_SEARCH_UPDATE = `${BASE}TERM_SEARCH_UPDATE`;
export const RESULTS_UPDATE = `${BASE}RESULTS_UPDATE`;
export const SEARCH_TYPE_UPDATE = `${BASE}SEARCH_TYPE_UPDATE`;
export const EPIC_ON_FOCUS_SEARCH = `${BASE}EPIC_ON_FOCUS_SEARCH`;
export const EPIC_MOVIES_LISTS_UPDATE = `${BASE}EPIC_MOVIES_LISTS_UPDATE`;
