const BASE = 'MOVIES/';

export const EPIC_MOVIE_LIST_GET = `${BASE}EPIC_MOVIE_LIST_GET`;
export const EPIC_MOVIE_LIST_GET_ON_SCROLL = `${BASE}EPIC_MOVIE_LIST_GET_ON_SCROLL`;
export const MOVIE_LIST_UPDATE = `${BASE}MOVIE_LIST_UPDATE`;
export const MOVIE_LIST_MORE_UPDATE = `${BASE}MOVIE_LIST_MORE_UPDATE`;
