const BASE = 'MOVIES/';

export default {
  EPIC_MOVIE_LIST_GET_ON_SCROLL: `${BASE}EPIC_MOVIE_LIST_GET_ON_SCROLL`,
  MOVIE_LIST_UPDATE: `${BASE}MOVIE_LIST_UPDATE`,
  MOVIE_LIST_MORE_UPDATE: `${BASE}MOVIE_LIST_MORE_UPDATE`
};
